theme: jekyll-theme-slate
title: Joseph Brant and the Digital Multiverse of History
description: An exploration of digitizing history
image: ![Image of Brant](https://github.com/EmileePetrie/Digitizing-History.md/blob/master/Portfolio%20picture%20Brant.PNG)
